import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import type { Tables, TablesInsert, TablesUpdate } from "@/integrations/supabase/types";
import { sendOrderEmail } from "./useOrderEmails";

export type Order = Tables<"orders"> & {
  order_items?: OrderItem[];
  customer_email?: string | null;
  payment_method?: string;
};

export type OrderInsert = TablesInsert<"orders">;
export type OrderUpdate = TablesUpdate<"orders">;
export type OrderStatus = Order["status"];
export type OrderType = Order["order_type"];

// Order item stored in order_items jsonb column
export interface OrderItem {
  id: string;
  templateId: string;
  templateName: string;
  cardName: string;
  quantity: number;
  unitPriceCents: number;
  photoUrl?: string | null;
  logoUrl?: string | null;
}

// Fetch user's orders
export function useUserOrders() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ["orders", user?.id],
    queryFn: async () => {
      if (!user) throw new Error("Not authenticated");
      
      const { data, error } = await supabase
        .from("orders")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as Order[];
    },
    enabled: !!user,
  });
}

// Fetch single order by ID
export function useOrder(orderId: string | undefined) {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ["order", orderId],
    queryFn: async () => {
      if (!user || !orderId) throw new Error("Missing data");
      
      const { data, error } = await supabase
        .from("orders")
        .select("*")
        .eq("id", orderId)
        .eq("user_id", user.id)
        .single();
      
      if (error) throw error;
      return data as Order;
    },
    enabled: !!user && !!orderId,
  });
}

// Create new COD order with cart items
export function useCreateOrder() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (orderData: {
      order_items: OrderItem[];
      quantity: number;
      unit_price_cents: number;
      total_price_cents: number;
      order_type?: "standard" | "personalized";
      template?: string;
      card_color?: string;
      logo_url?: string | null;
      background_type?: string;
      background_color?: string | null;
      background_image_url?: string | null;
      currency?: string;
      shipping_name?: string | null;
      shipping_phone?: string | null;
      shipping_address?: string | null;
      shipping_city?: string | null;
      shipping_postal_code?: string | null;
      shipping_country?: string | null;
      customer_email?: string | null;
      payment_method?: string;
      user_id?: string; // Allow passing user_id for newly created users
    }) => {
      // Get the current session to handle freshly created users
      const { data: sessionData } = await supabase.auth.getSession();
      const currentUserId = orderData.user_id || sessionData?.session?.user?.id || user?.id;
      
      if (!currentUserId) throw new Error("Not authenticated");
      
      // Prepare insert data - order_number generated by trigger
      const insertData: any = {
        user_id: currentUserId,
        order_items: orderData.order_items,
        quantity: orderData.quantity,
        unit_price_cents: orderData.unit_price_cents,
        total_price_cents: orderData.total_price_cents,
        order_type: orderData.order_type || "standard",
        template: orderData.template || "iwasp-signature",
        card_color: orderData.card_color || "white",
        logo_url: orderData.logo_url,
        background_type: orderData.background_type || "solid",
        background_color: orderData.background_color || "white",
        background_image_url: orderData.background_image_url,
        currency: orderData.currency || "EUR",
        status: "pending",
        shipping_name: orderData.shipping_name,
        shipping_phone: orderData.shipping_phone,
        shipping_address: orderData.shipping_address,
        shipping_city: orderData.shipping_city,
        shipping_postal_code: orderData.shipping_postal_code,
        shipping_country: orderData.shipping_country || "MA",
        customer_email: orderData.customer_email,
        payment_method: orderData.payment_method || "cod",
      };
      
      const { data, error } = await supabase
        .from("orders")
        .insert(insertData)
        .select()
        .single();
      
      if (error) throw error;
      return data as Order;
    },
    onSuccess: async (data) => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      toast.success("Commande créée avec succès");
      
      // Send confirmation email (async, don't block)
      sendOrderEmail({ orderId: data.id, emailType: "order_confirmation" })
        .then(success => {
          if (success) {
            console.log("Order confirmation email sent");
          } else {
            console.warn("Failed to send order confirmation email");
          }
        });
      
      return data;
    },
    onError: (error) => {
      console.error("Error creating order:", error);
      toast.error("Erreur lors de la création de la commande");
    },
  });
}

// Update order (only pending orders can be updated by user)
export function useUpdateOrder() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ orderId, updates }: { orderId: string; updates: OrderUpdate }) => {
      const { data, error } = await supabase
        .from("orders")
        .update(updates)
        .eq("id", orderId)
        .select()
        .single();
      
      if (error) throw error;
      return data as Order;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      queryClient.invalidateQueries({ queryKey: ["order", data.id] });
    },
    onError: (error) => {
      console.error("Error updating order:", error);
      toast.error("Erreur lors de la mise à jour de la commande");
    },
  });
}

// Get order status label in French
export function getOrderStatusLabel(status: OrderStatus): string {
  const labels: Record<OrderStatus, string> = {
    pending: "En attente de confirmation",
    paid: "Confirmée",
    in_production: "En production",
    shipped: "Expédiée",
    delivered: "Livrée",
  };
  return labels[status];
}

// Get order status color for badges
export function getOrderStatusColor(status: OrderStatus): string {
  const colors: Record<OrderStatus, string> = {
    pending: "bg-amber-100 text-amber-800",
    paid: "bg-blue-100 text-blue-800",
    in_production: "bg-purple-100 text-purple-800",
    shipped: "bg-indigo-100 text-indigo-800",
    delivered: "bg-green-100 text-green-800",
  };
  return colors[status];
}
