import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import type { Tables, TablesInsert, TablesUpdate } from "@/integrations/supabase/types";

export type Order = Tables<"orders">;
export type OrderInsert = TablesInsert<"orders">;
export type OrderUpdate = TablesUpdate<"orders">;
export type OrderStatus = Order["status"];
export type OrderType = Order["order_type"];

// Fetch user's orders
export function useUserOrders() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ["orders", user?.id],
    queryFn: async () => {
      if (!user) throw new Error("Not authenticated");
      
      const { data, error } = await supabase
        .from("orders")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as Order[];
    },
    enabled: !!user,
  });
}

// Fetch single order by ID
export function useOrder(orderId: string | undefined) {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ["order", orderId],
    queryFn: async () => {
      if (!user || !orderId) throw new Error("Missing data");
      
      const { data, error } = await supabase
        .from("orders")
        .select("*")
        .eq("id", orderId)
        .eq("user_id", user.id)
        .single();
      
      if (error) throw error;
      return data as Order;
    },
    enabled: !!user && !!orderId,
  });
}

// Create new COD order
export function useCreateOrder() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (orderData: Omit<OrderInsert, "user_id" | "order_number">) => {
      if (!user) throw new Error("Not authenticated");
      
      const { data, error } = await supabase
        .from("orders")
        .insert({
          ...orderData,
          user_id: user.id,
          order_number: "", // Will be auto-generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return data as Order;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      toast.success("Commande créée avec succès");
      return data;
    },
    onError: (error) => {
      console.error("Error creating order:", error);
      toast.error("Erreur lors de la création de la commande");
    },
  });
}

// Update order (only pending orders can be updated by user)
export function useUpdateOrder() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ orderId, updates }: { orderId: string; updates: OrderUpdate }) => {
      const { data, error } = await supabase
        .from("orders")
        .update(updates)
        .eq("id", orderId)
        .select()
        .single();
      
      if (error) throw error;
      return data as Order;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      queryClient.invalidateQueries({ queryKey: ["order", data.id] });
    },
    onError: (error) => {
      console.error("Error updating order:", error);
      toast.error("Erreur lors de la mise à jour de la commande");
    },
  });
}

// Get order status label in French
export function getOrderStatusLabel(status: OrderStatus): string {
  const labels: Record<OrderStatus, string> = {
    pending: "En attente de confirmation",
    paid: "Confirmée",
    in_production: "En production",
    shipped: "Expédiée",
    delivered: "Livrée",
  };
  return labels[status];
}

// Get order status color for badges
export function getOrderStatusColor(status: OrderStatus): string {
  const colors: Record<OrderStatus, string> = {
    pending: "bg-amber-100 text-amber-800",
    paid: "bg-blue-100 text-blue-800",
    in_production: "bg-purple-100 text-purple-800",
    shipped: "bg-indigo-100 text-indigo-800",
    delivered: "bg-green-100 text-green-800",
  };
  return colors[status];
}
