// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Les valeurs du projet sont publiques par conception (URL + clé publishable/anon)
// et sont écrites en dur pour garantir leur présence dans le bundle de production,
// même si les variables d'environnement ne sont pas injectées au build de publication.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://vwlngxifajsziexhkafe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "sb_publishable_K9qQTKdVJG-k5-OKdSqZBw_DrURXgVV";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // PKCE : requis pour le flux OAuth mobile (navigateur système + deep link +
    // exchangeCodeForSession). Sur le web, supabase-js échange automatiquement le
    // `?code=` au retour (detectSessionInUrl) — le parcours web reste inchangé.
    flowType: 'pkce',
    detectSessionInUrl: true,
  }
});
