// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // PKCE : requis pour le flux OAuth mobile (navigateur système + deep link +
    // exchangeCodeForSession). Sur le web, supabase-js échange automatiquement le
    // `?code=` au retour (detectSessionInUrl) — le parcours web reste inchangé.
    flowType: 'pkce',
    detectSessionInUrl: true,
  }
});